import random
import sys
from PyQt6 import QtGui, QtWidgets, uic
from PyQt6.QtCore import Qt

# Form implementation generated from reading ui file 'C:\Users\UserHome\PycharmProjects\pythonProject1\UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(406, 300)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 260, 171, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Нарисовать 3 окружности"))


class MainWindow(QtWidgets.QMainWindow, Ui_Form):
    def __init__(self):
        super().__init__()

        self.label = QtWidgets.QLabel()
        canvas = QtGui.QPixmap(400, 300)
        canvas.fill(Qt.GlobalColor.white)
        self.setupUi(self)
        self.pushButton.clicked.connect(self.draw_something)
        self.label.setPixmap(canvas)

    def draw_something(self):
        self.setCentralWidget(self.label)
        canvas = self.label.pixmap()
        painter = QtGui.QPainter(canvas)
        pen = QtGui.QPen()
        pen.setWidth(3)
        color = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
        pen.setColor(QtGui.QColor(*color))
        painter.setPen(pen)
        brush = QtGui.QBrush()
        brush.setColor(QtGui.QColor(*color))
        brush.setStyle(Qt.BrushStyle.Dense1Pattern)
        painter.setBrush(brush)
        w1, w2, w3 = random.randint(10, 100), random.randint(10, 100), random.randint(10, 100)
        painter.drawEllipse(60, 60, w1, w1)
        painter.drawEllipse(200, 220, w2, w2)
        painter.drawEllipse(300, 70, w3, w3)
        painter.end()
        self.label.setPixmap(canvas)


app = QtWidgets.QApplication(sys.argv)
window = MainWindow()
window.show()
app.exec()